# Generated by Django 2.2 on 2020-08-13 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movies.BaseModel')),
                ('name', models.CharField(max_length=20)),
            ],
            bases=('movies.basemodel',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movies.BaseModel')),
                ('name', models.CharField(max_length=100)),
                ('popularity', models.FloatField(default=0.0)),
                ('imdb_score', models.FloatField(default=0.0)),
                ('director', models.CharField(max_length=100)),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
            bases=('movies.basemodel',),
        ),
    ]
